build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  tags:
    - 'cluster:hindawi-dev'

test-job1:
  stage: test
  script:
    - ping google.com
  tags:
    - 'cluster:hindawi-dev'

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
  tags:
    - 'cluster:hindawi-dev'  

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - 'cluster:hindawi-dev'