FROM node:14-alpine as build

RUN apk update && apk upgrade && \
  apk add --no-cache bash git openssh g++ make python

ENV HOME "/home/app"

WORKDIR ${HOME}

# Copy package.json to the working directory
COPY package.json yarn.lock ./

# Install any needed packages specified in package.json
RUN yarn install --frozen-lockfile

# Copying the rest of the code to the working directory
COPY ./ ./
RUN rm -rf dist

# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1170
ENTRYPOINT [ "" ]
