FROM node:16-alpine
ENV HOME "/home/app"
WORKDIR ${HOME}

RUN apk add --no-cache \
  bash \
  ca-certificates \
  g++ \
  git \
  make \
  nss \
  openssh \
  python3 \
  py3-pip

# Copy package.json to the working directory
COPY package.json yarn.lock ./

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
# Install any needed packages specified in package.json
RUN yarn install --frozen-lockfile --production


ENTRYPOINT [ "" ]

