import { INVOICE_QUERY } from './queries';

import {
  APPLY_COUPON_MUTATION,
  CREATE_CREDIT_NOTE_MUTATION,
  BANK_TRANSFER_MUTATION,
} from './mutations';

export {
  // queries
  INVOICE_QUERY,
  // mutations
  CREATE_CREDIT_NOTE_MUTATION,
  APPLY_COUPON_MUTATION,
  BANK_TRANSFER_MUTATION,
};
