import { COUPON_UPDATE_MUTATION, COUPON_CREATE_MUTATION } from './mutations';
import { COUPON_QUERY, COUPON_FRAGMENT } from './queries';

export {
  COUPON_QUERY,
  COUPON_FRAGMENT,
  COUPON_UPDATE_MUTATION,
  COUPON_CREATE_MUTATION,
};
