/**
 * * Enumerates the possible user roles.
 */
export enum Roles {
  DOMAIN_EVENT_HANDLER = 'DOMAIN_EVENT_HANDLER',
  QUEUE_EVENT_HANDLER = 'QUEUE_EVENT_HANDLER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  CHRON_JOB = 'CHRON_JOB',
  CUSTOMER = 'CUSTOMER',
  SERVICE = 'SERVICE',
  AUTHOR = 'AUTHOR',
  PUBLIC = 'PUBLIC',
  PAYER = 'PAYER',
  ADMIN = 'ADMIN',

  FINANCIAL_CONTROLLER = 'FINANCIAL_CONTROLLER',
  FINANCIAL_SUPPORT = 'FINANCIAL_SUPPORT',
  FINANCIAL_ADMIN = 'FINANCIAL_ADMIN',
  FINANCIAL_BASIC = 'FINANCIAL_BASIC',
  MARKETING = 'MARKETING',
}
