/**
 * * Enumerates the possible user roles.
 */
export enum Roles {
  DOMAIN_EVENT_HANDLER = 'DOMAIN_EVENT_HANDLER',
  QUEUE_EVENT_HANDLER = 'QUEUE_EVENT_HANDLER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  CUSTOMER = 'CUSTOMER',
  SERVICE = 'SERVICE',
  AUTHOR = 'AUTHOR',
  PUBLIC = 'PUBLIC',
  CHRON_JOB = 'CHRON_JOB',
  PAYER = 'PAYER',
  ADMIN = 'ADMIN',
}
