const stylesObject = {
  'body,\n      html': { font: '8px sans-serif', color: '#6f7a79' },
  '#pageFooter': {
    fontSize: '0.9rem',
    borderTop: '0.2rem solid #d3d6d6',
    paddingTop: '0.5rem',
    textAlign: 'center',
  },
  '#pageFooter h2': { fontSize: '1rem', margin: '0', padding: '0' },
  '#pageFooter p': { margin: '0', padding: '0' },
  '#pageHeader': { position: 'relative' },
  '#pageHeader h2': {
    fontWeight: 'normal',
    fontSize: '1.5rem',
    textTransform: 'uppercase',
    textAlign: 'center',
    paddingTop: '3rem',
  },
  '#pageHeader img': {
    position: 'absolute',
    left: '0',
    top: '0',
    maxWidth: '20rem',
    minHeight: '30px',
    maxHeight: '50px',
  },
  p: { margin: '0' },
  a: { color: '#006f92' },
  h1: {
    borderBottom: '0.25rem solid',
    color: '#006f92',
    fontSize: '1.1rem',
    padding: '0.2rem 0',
    marginBottom: '1.8rem',
  },
  h3: { fontSize: '1rem', fontWeight: 'normal', margin: '0' },
  'h1.withSubheader': { marginBottom: '0' },
  'h1.withSubheader + p': { margin: '0 0 1rem 0' },
  'table.data': {
    borderCollapse: 'collapse',
    height: '100%',
    width: '100%',
    fontSize: '1rem',
  },
  'table.data th': { width: '40%' },
  'table.data th em': { fontWeight: 'normal', fontStyle: 'normal' },
  'table.data th,\n      table.data td': {
    margin: '0',
    padding: '0.5rem 0',
    textAlign: 'left',
    verticalAlign: 'top',
  },
  'table.data.billing th em': { fontWeight: 'normal' },
  'th.summary,\n      td.summary': { borderTop: '0.1rem solid' },
  'table.columns': {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '100%',
  },
  'table.columns table': { width: '100%', height: '100%' },
  'table.columns td': {
    width: '47%',
    verticalAlign: 'top',
    textAlign: 'left',
    paddingLeft: '3%',
  },
  'table.columns td:first-child': { paddingLeft: '0', paddingRight: '3%' },
  '.separator': {
    borderTop: '0.125rem solid',
    padding: '0.5rem 0',
    margin: '1rem 0',
  },
  '.isCentered': { textAlign: 'center' },
  '.cards': {
    margin: '12px',
    border: '1px solid #ccc',
    borderRadius: '3px',
    padding: '6px',
    height: '3.6rem',
  },
};

export { stylesObject };
