export default {
  UPDATE: "@prefix/payer/UPDATE",
  CREATE_PAYMENT: "@prefix/payer/CREATE_PAYMENT",
  CREATE_PAYMENT_FULFILLED: "@prefix/payer/CREATE_PAYMENT_FULFILLED",
  CREATE_PAYPAL_PAYMENT: "@prefix/payer/CREATE_PAYPAL_PAYMENT",
  CREATE_PAYPAL_PAYMENT_FULFILLED: "@prefix/payer/CREATE_PAYPAL_PAYMENT_FULFILLED",
} as const;
