apiVersion: batch/v1 
kind: Job 
metadata:   
  name: kubernetes-netsuite-cleanup-job   
  labels:     
    jobgroup: netsuite 
spec:   
  template:     
    metadata:       
      name: kubejob       
      labels:         
        jobgroup: netsuite     
    spec:       
      containers:       
      - name: netsuite-terminator          
        image: 916437579680.dkr.ecr.eu-west-1.amazonaws.com/belzebuth-playground:netsuite-pacifier-0.4.0         
        env:
        - name: RECORD_TYPE
          value: "customerpayment"
        - name: BATCH_SIZE
          value: "200"
        - name: DELAY
          value: "200"
        - name: NETSUITE_REALM
          value: "6416429_SB1"
        - name: NETSUITE_REST_ENDPOINT
          value: "https://6416429-sb1.suitetalk.api.netsuite.com/services/rest"
        - name: NETSUITE_CONSUMER_KEY
          value: "<placeholder>"
        - name: NETSUITE_CONSUMER_SECRET
          value: "<placeholder>"
        - name: NETSUITE_TOKEN_ID
          value: "<placeholder>"
        - name: NETSUITE_TOKEN_SECRET
          value: "<placeholder>"
      restartPolicy: OnFailure