{{- $hasFeature := dict "envVars" false -}}
{{- if .Values.envVars -}}
  {{- $_ := set $hasFeature "envVars" true -}}
{{- end -}}
{{- if .Values.sso.enabled -}}
  {{- $_ := set $hasFeature "envVars" true -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    app: {{ include "superset.name" . }}
    chart: {{ include "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "superset.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "superset.fullname" . }}
      labels:
        app: {{ include "superset.name" . }}
        chart: {{ include "superset.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.deploymentAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      {{- if .Values.sso.enabled }}
      volumes:
        - name: superset-configs
          secret:
            secretName: {{ include "superset.fullname" . }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      initContainers:
        - name: db-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['bash', '-c', "superset db upgrade && superset init"]
          {{- if index $hasFeature "envVars" }}
          env:
            {{- range $key, $value := .Values.envVars }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
          {{- if .Values.extraEnvFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.extraEnvFromSecret }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.sso.enabled }}
          volumeMounts:
            - name: superset-configs
              mountPath: /home/superset/secrets
          {{- end }}
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          {{- if index $hasFeature "envVars" }}
          env:
            {{- range $key, $value := .Values.envVars }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            {{- if .Values.sso.enabled }}
            - name: OIDC_CLIENT_SECRETS_PATH
              value: '/home/superset/secrets'
            {{- end }}
          {{- end }}
          {{- if .Values.extraEnvFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.extraEnvFromSecret }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
